Repository jupyter-server/gateway_provisioners, pull requests merged in 2023-03, with the labels that each got.

#66 Add application support information for deploying JKG and Lab
  .pre-commit-config.yaml
  Makefile
  docs/source/contributors/devinstall.md
  docs/source/index.rst
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  gateway_provisioners/app-support/README.md
  gateway_provisioners/app-support/docker/Dockerfile
  gateway_provisioners/app-support/docker/start-application.sh
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/Chart.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/daemonset.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/deployment.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/gp-clusterrole.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/gp-clusterrolebinding.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/gp-serviceaccount.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/imagepullSecret.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/ingress.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/kip-clusterrole.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/kip-clusterrolebinding.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/kip-serviceaccount.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/psp.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/templates/service.yaml
  gateway_provisioners/app-support/kubernetes/helm/gateway-provisioners/values.yaml
  gateway_provisioners/docker/server-image/Dockerfile
Labels: documentation, enhancement, deployment, kubernetes

#68 Fix relative link formatting in documentation to be consistent
  docs/source/contributors/devinstall.md
  docs/source/contributors/system-architecture.md
Labels: documentation, maintenance

#67 Fix minor errors in Users subsection of documentation
  docs/source/users/connecting-to-a-gateway.md
  docs/source/users/index.rst
  docs/source/users/kernel-envs.md
Labels: bug, documentation

#71 Fix typos in App Support README
  gateway_provisioners/app-support/README.md
Labels: bug

#72 Fix grammar NITs in Operator's Guide of docs
  docs/source/operators/config-add-env.md
  docs/source/operators/config-env-debug.md
  docs/source/operators/config-kernel-override.md
  docs/source/operators/config-security.md
  docs/source/operators/deploy-distributed.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/deploy-yarn-cluster.md
  docs/source/operators/index.rst
  docs/source/operators/installing-gp-container.md
  docs/source/operators/installing-kernels-container.md
  docs/source/operators/installing-kernels.md
Labels: documentation

#74 Fix minor issues in Developer and Contributor docs
  docs/source/contributors/devinstall.md
  docs/source/contributors/system-architecture.md
  docs/source/developers/custom-images.md
  docs/source/developers/dev-remote-provisioner.md
  docs/source/developers/kernel-launcher.md
Labels: documentation
