Repository jupyter-server/gateway_provisioners, pull requests merged in 2023-02, with the labels that each got.

#55 Cleanup users guide
  README.md
  docs/source/conf.py
  docs/source/contributors/sequence-diagrams.md
  docs/source/users/connecting-to-a-gateway.md
  docs/source/users/connecting-to-eg.md
  docs/source/users/index.rst
  docs/source/users/kernel-envs.md
  gateway_provisioners/k8s.py
Labels: documentation

#57 Cleanup operators guide
  Makefile
  docs/Makefile
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/operators/config-add-env.md
  docs/source/operators/config-file.md
  docs/source/operators/config-kernel-override.md
  docs/source/operators/config-security.md
  docs/source/operators/deploy-distributed.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/deploy-yarn-cluster.md
  docs/source/operators/index.rst
  docs/source/operators/installing-gp-container.md
  docs/source/operators/installing-gp.md
  docs/source/operators/installing-kernels-container.md
  docs/source/operators/installing-kernels.md
  gateway_provisioners/cli/base_app.py
  gateway_provisioners/cli/docker_specapp.py
  gateway_provisioners/cli/k8s_specapp.py
  gateway_provisioners/cli/ssh_specapp.py
  gateway_provisioners/cli/yarn_specapp.py
  gateway_provisioners/container.py
  gateway_provisioners/distributed.py
  gateway_provisioners/docker/gp-spark-base/Dockerfile
  gateway_provisioners/docker/kernel-image/Dockerfile
  gateway_provisioners/k8s.py
  gateway_provisioners/kernel-launchers/docker/scripts/launch_docker.py
  gateway_provisioners/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2
  gateway_provisioners/yarn.py
  pyproject.toml
Labels: documentation

#58 Cleanup Developers Guide
  Makefile
  docs/source/contributors/devinstall.md
  docs/source/contributors/index.rst
  docs/source/developers/custom-images.md
  docs/source/developers/dev-remote-provisioner.md
  docs/source/developers/index.rst
  docs/source/developers/kernel-launcher.md
  docs/source/developers/kernel-specification.md
Labels: documentation

#59 Cleanup Contributors Guide, remove Other section
  docs/source/conf.py
  docs/source/contributors/contrib.md
  docs/source/contributors/debug.md
  docs/source/contributors/devinstall.md
  docs/source/contributors/docker.md
  docs/source/contributors/index.rst
  docs/source/contributors/related-resources.md
  docs/source/contributors/sequence-diagrams.md
  docs/source/contributors/system-architecture.md
  docs/source/developers/kernel-launcher.md
  docs/source/images/debug_configuration.png
  docs/source/images/deployment.png
  docs/source/images/process_proxy_hierarchy.png
  docs/source/images/yarnui.jpg
  docs/source/index.rst
  docs/source/operators/deploy-distributed.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/installing-gp-container.md
  docs/source/operators/installing-gp.md
  docs/source/other/index.rst
  docs/source/other/troubleshooting.md
  pyproject.toml
Labels: documentation

#60 Add replace option to prevent accidental overwrite
  gateway_provisioners/cli/base_app.py
Labels: enhancement

#62 Replace references to gateway-experiments with jupyter-server
  README.md
  docs/source/contributors/devinstall.md
  docs/source/contributors/related-resources.md
  docs/source/contributors/system-architecture.md
  docs/source/developers/custom-images.md
  docs/source/developers/dev-remote-provisioner.md
  docs/source/developers/kernel-launcher.md
  docs/source/developers/kernel-specification.md
  docs/source/index.rst
  docs/source/operators/config-security.md
  docs/source/operators/deploy-distributed.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/deploy-yarn-cluster.md
  docs/source/operators/installing-kernels-container.md
  pyproject.toml
Labels: documentation

#63 Create hatch build env with make-related scripts
  .pre-commit-config.yaml
  Makefile
  gateway_provisioners/cli/base_app.py
  gateway_provisioners/cli/image_bootstrapapp.py
  gateway_provisioners/config_mixin.py
  gateway_provisioners/docker_swarm.py
  gateway_provisioners/k8s.py
  gateway_provisioners/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
  gateway_provisioners/kernel-launchers/shared/scripts/server_listener.py
  gateway_provisioners/remote_provisioner.py
  pyproject.toml
  tests/mocks/yarn_client.py
  tests/test_docker_provisioners.py
  tests/test_k8s_provisioners.py
  tests/test_yarn_provisioners.py
Labels: maintenance

#64 Use releaser workflows
  RELEASING.md
Labels: maintenance
