Repository jupyter-server/gateway_provisioners, pull requests merged in 2023-01, with the labels that each got.

#40 Add CI workflow
  .github/codeql/codeql-config.yml
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  docs/Makefile
  docs/doc-requirements.txt
  docs/remote_provisioners.cli.rst
  docs/remote_provisioners.rst
  docs/remote_provisioners.tests.rst
  docs/source/api/gateway_provisioners.cli.rst
  docs/source/api/gateway_provisioners.rst
  docs/source/api/modules.rst
  docs/source/conf.py
  docs/source/contributors/devinstall.md
  docs/source/contributors/index.rst
  docs/source/contributors/system-architecture.md
  docs/source/developers/index.rst
  docs/source/operators/config-security.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/deploy-yarn-cluster.md
  gateway_provisioners/__init__.py
  gateway_provisioners/cli/base_app.py
  gateway_provisioners/cli/docker_specapp.py
  gateway_provisioners/cli/image_bootstrapapp.py
  gateway_provisioners/cli/k8s_specapp.py
  gateway_provisioners/cli/ssh_specapp.py
  gateway_provisioners/cli/yarn_specapp.py
  gateway_provisioners/config_mixin.py
  gateway_provisioners/container.py
  gateway_provisioners/distributed.py
  gateway_provisioners/docker_swarm.py
  gateway_provisioners/k8s.py
  gateway_provisioners/kernel-launchers/docker/scripts/launch_docker.py
  gateway_provisioners/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
  gateway_provisioners/kernel-launchers/operators/scripts/launch_custom_resource.py
  gateway_provisioners/kernel-launchers/python/scripts/launch_ipykernel.py
  gateway_provisioners/kernel-launchers/python/scripts/server_listener.py
  gateway_provisioners/kernel-launchers/shared/scripts/server_listener.py
  gateway_provisioners/remote_provisioner.py
  gateway_provisioners/response_manager.py
  gateway_provisioners/tests/__init__.py
  gateway_provisioners/tests/conftest.py
  gateway_provisioners/tests/test_provider.py
  gateway_provisioners/tests/test_spec_utils.py
  gateway_provisioners/yarn.py
  pyproject.toml
Labels: documentation, maintenance

#44 Add notice on main page regarding transition from EG
  docs/source/index.rst
Labels: documentation, maintenance

#46 Initial test framework and tests
  .github/workflows/build.yml
  Makefile
  gateway_provisioners/container.py
  gateway_provisioners/distributed.py
  gateway_provisioners/docker_swarm.py
  gateway_provisioners/k8s.py
  gateway_provisioners/remote_provisioner.py
  gateway_provisioners/yarn.py
  pyproject.toml
  tests/conftest.py
  tests/mocks/__init__.py
  tests/mocks/docker_client.py
  tests/mocks/k8s_client.py
  tests/mocks/popen.py
  tests/mocks/response_manager.py
  tests/mocks/yarn_client.py
  tests/test_docker_provisioners.py
  tests/test_k8s_provisioners.py
  tests/test_yarn_provisioners.py
  tests/validators.py
Labels: maintenance, testing

#47 Prepare for initial release
  .github/release.yml
  .github/workflows/build.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  LICENSE
  LICENSE.md
  Makefile
  README.md
  RELEASING.md
  docs/source/contributors/devinstall.md
  pyproject.toml
Labels: maintenance

#48 Clean up lint and add check release
  .github/workflows/build.yml
  CHANGELOG.md
  Makefile
  docs/source/contributors/devinstall.md
  pyproject.toml
Labels: maintenance

#49 Fix default tooling
  gateway_provisioners/cli/base_app.py
Labels: bug
